import "./ContentRight.scss";
const ContentRight = () => {
	return (
		<div className="ContentRight">
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
			asdfadsf <br/>
		</div>
	)
}
export default ContentRight;