import globalClassNames from "../../../style.d";
declare const classNames: typeof globalClassNames & {
  readonly Profile: ProfileNames;
  readonly Preview: ProfileNames;
  readonly Hover: ProfileNames;
  readonly Small: ProfileNames;
  readonly Cover: ProfileNames;
  readonly Edit: ProfileNames;
  readonly EditAvatar: ProfileNames;
  readonly Actions: ProfileNames;
  readonly FixedWidthButton: ProfileNames;
  readonly Title: ProfileNames;
  readonly NameAndVerified: ProfileNames;
  readonly Verified: ProfileNames;
  readonly Username: ProfileNames;
  readonly ProfileInfo: ProfileNames;
  readonly Bio: ProfileNames;
  readonly Friendship: ProfileNames;
  readonly Loading: ProfileNames;
  readonly Tweets: ProfileNames;
};
export = classNames;
